### ISSUE TITLE
Infrastructure Setup

### ISSUE THREAD

**Issue by lbighetti** [lbighetti/hades#3]
- [x] CircleCI
- [x] Code Coverage Tool @webofbits
- [x] Code Analysis (Credo) @webofbits
- [x] Setup Nanobox @lbighetti
    - [x] local dev
    - [x] local test
    - [x] document in README how to run project locally with nanobox

----

Let's leave staging for a later time

**Comment by lbighetti** [comment]
example yaml for Circle CI to deploy to Nanobox (using ruby and other random stuff, but we should be able use parts of it)

```yaml
version: 2

jobs:
  build-job:
    machine: true
    steps:
      - checkout
      - run: sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"

      - run: nanobox evar add local CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
      - run: nanobox evar add local CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
      - run: nanobox evar add local CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
      - run: nanobox evar add local CLOUDINARY_SECURE=$CLOUDINARY_SECURE
      - run: nanobox evar add local KEY_ENCRYPTION_KEY=$KEY_ENCRYPTION_KEY
      - run: nanobox evar add local MAXMIND_API_KEY=$MAXMIND_API_KEY
      - run: nanobox evar add local NANOBOX_PASSWORD=$NANOBOX_PASSWORD
      - run: nanobox evar add local NANOBOX_USERNAME=$NANOBOX_USERNAME
      - run: nanobox evar add local OPENCAGE_API_KEY=$OPENCAGE_API_KEY
      - run: nanobox evar add local RAILS_ENV=$RAILS_ENV
      - run: nanobox evar add local SECRET_KEY_BASE=$SECRET_KEY_BASE
      - run: nanobox evar add local NANOBOX=true
      - run: nanobox evar add local RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY
      - run: nanobox evar add local RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
      - run: nanobox run bundle exec rake db:create db:test:prepare
      - run: SLOW_SPECS=true REMOTE_SPECS=true nanobox run bundle exec rspec
      - run: nanobox run bundle exec teaspoon

  deploy-job:
    machine: true
    steps:
      - checkout
      - run: sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"

      - run: nanobox remote add my-app
      - run: nanobox deploy -m "$(git log --format=format:"%s (%h)" -n 1 $CIRCLE_SHA1)"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master

```

**Comment by ccarvalho-eng** [comment]
For elixir basic building it should be something like this:
```
version: 2
jobs:
  build:
    working_directory: ~/cci-demo-phoenix
    docker:
      - image: elixir:1.5.2
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
```
![screenshot from 2017-12-18 21-33-56](https://user-images.githubusercontent.com/14858867/34134745-590d2cfa-e43b-11e7-8e42-a73ab9894ff1.png)

You need to give me access, maybe adding me as a contributor on Circle CI Dashboard.
